
  # ── __CF_APP_NAME__ Secret Stack ─────────────────────────────────────────
  __CF_APP_NAME__SecretStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rpx.cf.ecs.template.nonprod.s3.us-east-1.amazonaws.com/templates/secret-manager.yaml
      Parameters:
        Environment: __ENVIRONMENT__
        AppName: __APP_NAME__
      Tags:
        - Key: Environment
          Value: __ENVIRONMENT__
        - Key: ManagedBy
          Value: CloudFormation
