AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager Stack - function-manager secret

Resources:
  SampleSecretStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://abc.cf.ecs.template.nonprod.s3.us-east-1.amazonaws.com/templates/secret-manager.yaml
      Parameters:
        Environment: dev
        AppName: acquiflow
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
  # ── Sampleservice Secret Stack ─────────────────────────────────────────
  SampleserviceSecretStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rpx.cf.ecs.template.nonprod.s3.us-east-1.amazonaws.com/templates/secret-manager.yaml
      Parameters:
        Environment: dev
        AppName: sample-service
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
